### PR TITLE
Bugfix postrelease

### LINKED ISSUE #4: CRAN Submission 1.6-1: Need for reference
On 2023-09-19, CRAN asked the following:
For future submissions:
Is there some reference about the method you can add in the Description field in the form Authors (year) <doi:10.....> or <arXiv:.....>?

### LINKED ISSUE #5: CCInter / CSInter: Error if there is 0 in one of the 2by2 tables
Hi Epiconcept team :)
When using the function ccinter in EpiStats, if there is a 0 in my 2 by 2 table, I get the error message as pasted below. I imagine it is because the logistic regression cannot run with a zero in the cell. Could you kindly create a more informative error message?
All the best,
Esther
image

### LINKED ISSUE #6: cctable and cc will not run if one variable listed includes only 1s or only 0s
If a one of the variables that wish to test with cctable contains only 1 or only 0, then the function returns an error.

image

A similar error appears in cc()
image

### LINKED ISSUE #7: cc does not recognise variable names when inserted in the form of an object
cc only recognises variable names if input in character format. 
If assign the variable to an object, or assign it in a for loop then the function cannot identify the variable and returns an error.
image

### LINKED ISSUE #8: CCInter line 126: retrieveLast
In the CCInter() function, there is a function retrieveLast() for which I am unsure this is the desired behaviour for the function.
To check with @Estherki :)

### LINKED ISSUE #10: Change title of CCTable and CSTable
CCtable would give: Tot.Cases Exp.Cases %Cases Tot.Ctrls Exp.Ctrls %Ctrls
CStable would give: Tot.Exp Cases.Exp AR.Exp% Tot.Unexp Cases.Unexp AR.Unexp%

### PR DESCRIPTION
**Pull request by loremerdrignac**
Dear @epi-jhd and @Estherki 

I tried to fix issues #4, #5, #6 and #7 in the branch 'bugfix_postrelease'.
Could I kindly ask you to have look and test that the bugs you found either are fixed or return a nicer Error message?

@Estherki, for issue #5, I could not reproduce the exact same error message. Possibly my fix does not cover your issue. Could I kindly ask you to share the corresponding dataset so that I investigate further?

Thank you both!!

### CODE REVIEW

**Comment by epi-jhd** [comment]
I can confirm that issues 6 and 7 are resolved.

**Comment by loremerdrignac** [comment]
Dear @epi-jhd,
I had to make some additional fixes for issue #5 using a test dataset provided by @Estherki. Could I kindly ask you whether issues 6 and 7 and still solved with this latest version of the package?
Many thanks in advance!

**Comment by epi-jhd** [comment]
Dear @loremerdrignac 
I've checked the latest version of the functions cctab and cc and issues 6 and 7 are still solved. 
To note: I no longer see automatic display of a results summary as I did for cc - is this intended?
thanks!

**Comment by loremerdrignac** [comment]
Thank you @epi-jhd for reviewing it again! :)
We saw together that the automatic display works only if we do not store the output of the function in a R object.
Unless I am mistaken :-/ it used to be like that before, but if needed we can change this behaviour! 
I create a new issue for the other aesthetic issue that you spotted ;) thank you!!

**Comment by loremerdrignac** [comment]
@loremerdrignac to solve issue #8 and #10 before new round of tests :)

**Comment by loremerdrignac** [comment]
Dear @epi-jhd 
Me again.... :) Could I kindly ask you whether the column names for CCTable and CSTable are fine by you?
All issues from 4 to 10 should hopefully be covered in this version of the package (fingers crossed!).
Thank you!!

**Pull request merged**
